#!/bin/bash

hpack
cabal v2-install xmonad --overwrite-policy=always
cabal v2-install xmobar --overwrite-policy=always
cabal v2-build .
config="$(cabal v2-exec which xmonad-config)"
[ -n "$1" ] && cp -f "$config" "$1"
