#!/bin/bash

hpack
cabal v2-install xmonad --overwrite-policy=always
cabal v2-install xmobar --overwrite-policy=always
cabal v2-install . --overwrite-policy=always
[ -n "$1" ] && ln -sf $HOME/.local/bin/xmonad-config "$1"
