name: xmonad-config
version: '0.1.0.0'
synopsis: My xmonad config
license: BSD3
author: Nikolay Yakimov
maintainer: root@livid.pp.ru
copyright: 2016 Nikolay Yakimov
category: System
github: lierdakil/xmonad-config
dependencies:
- base
default-extensions:
  - LambdaCase
  - GHC2021
  - OverloadedStrings
  - RecordWildCards
  - DerivingStrategies
ghc-options: -Wall
data-files:
  xmobar/icons/*.xbm
library:
  source-dirs: lib
  dependencies:
  - xmonad
  - xmonad-contrib
  - bytestring
  - data-default
  - mtl
  - aeson
  - connection
  - http-conduit
  - text
executables:
  xmonad-config:
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    main: xmonad.hs
    source-dirs: src
    dependencies:
    - xmonad-config
    - xmonad
    - xmonad-contrib
    - containers
    - clock
  xmonadctl:
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    main: xmonadctl.hs
    source-dirs: src
    dependencies:
    - X11
  xmobar:
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    main: xmobar.hs
    source-dirs: xmobar
    dependencies:
    - xmobar
    - filepath
    - text
    - process
    - containers
